version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn --version # Check Maven is installed correctly
  build:
    commands:
      - echo Building, Testing, and Packaging the application...
      - mvn clean package
  post_build:
    commands:
      - echo Build, Testing, and Packaging completed.
      - ls target/ # Verify artifact generation
artifacts:
  files:
    - target/*.jar
  discard-paths: true

cache:
  paths:
    - '/root/.m2/**/*'
